# Generated by Django 2.1.7 on 2019-05-07 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='extra_food_purchased',
        ),
        migrations.AlterField(
            model_name='tripitinerary',
            name='trips',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.trips'),
        ),
    ]
