# Generated by Django 2.1.7 on 2019-05-11 03:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripitinerary',
            name='it_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tripitinerary',
            name='itinerary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
