# Generated by Django 2.1.7 on 2019-03-16 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190316_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vans',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.trailers'),
        ),
    ]
