# Generated by Django 2.1.7 on 2019-05-11 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190510_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripitinerary',
            old_name='it_title',
            new_name='Itinerary_title',
        ),
    ]
