# Generated by Django 2.1.7 on 2019-05-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190503_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='trip_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='trip_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
