# Generated by Django 2.1.7 on 2019-03-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190316_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trailers',
            options={'verbose_name_plural': 'trailers'},
        ),
        migrations.AlterField(
            model_name='trips',
            name='extra_food_purchased',
            field=models.ManyToManyField(blank=True, null=True, related_name='food_used', to='inventory.food'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='extra_meals_purchased',
            field=models.ManyToManyField(blank=True, null=True, related_name='trip_meals', to='inventory.meal'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='extra_supplies',
            field=models.ManyToManyField(blank=True, null=True, related_name='trip_extras', to='inventory.supplies'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='kayak_used',
            field=models.ManyToManyField(blank=True, null=True, related_name='kayak', to='inventory.kayak'),
        ),
    ]
