# Generated by Django 2.1.7 on 2019-05-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190503_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vans',
            name='comments',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
