# Generated by Django 2.1.7 on 2019-05-11 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190510_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='trip_Itinerary',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.tripItinerary'),
            preserve_default=False,
        ),
    ]
