# Generated by Django 2.1.7 on 2019-04-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190318_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='extra_food_purchased',
            field=models.ManyToManyField(blank=True, related_name='food_used', to='inventory.food'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='extra_meals_purchased',
            field=models.ManyToManyField(blank=True, related_name='trip_meals', to='inventory.meal'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='extra_supplies',
            field=models.ManyToManyField(blank=True, related_name='trip_extras', to='inventory.supplies'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='kayak_used',
            field=models.ManyToManyField(blank=True, related_name='kayak', to='inventory.kayak'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='trip_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='trip_start',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='van_used',
            field=models.ManyToManyField(blank=True, to='inventory.vans'),
        ),
    ]
