# Generated by Django 2.1.7 on 2019-05-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_trips_trip_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='comment',
            field=models.CharField(default='none', max_length=220),
            preserve_default=False,
        ),
    ]
