# Generated by Django 2.1.7 on 2019-05-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190503_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van_kit',
            name='comments',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
