# Generated by Django 2.1.7 on 2019-05-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20190503_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_meals',
            name='meal_qty',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
